[config]
btn_analog1x_left = 30
btn_analog1x_right = 32
btn_analog1y_down = 31
btn_analog1y_up = 17
btn_analog2x_left = 75
btn_analog2x_right = 77
btn_analog2y_down = 80
btn_analog2y_up = 72
btn_dpad_left = 33
btn_dpad_right = 35
btn_dpad_down = 34
btn_dpad_up = 20
btn_trigger_left = 73
btn_trigger_right = 81
btn_a = 83
btn_b = 79
btn_x = 82
btn_y = 71
btn_lb = 27
btn_rb = 43
btn_l3 = 26
btn_r3 = 40
btn_back = 12
btn_start = 13
btn_guide = 11
btn_stick_alternate_onoff = 58
btn_trigger_alternate_onoff = 54
btn_trigger_left_low = -174
btn_trigger_left_high = -179
btn_trigger_right_low = -175
btn_trigger_right_high = -176
btn_trigger_left_reduce = 1071
btn_trigger_right_reduce = 1075
btn_analog1x_reset = 16
btn_analog1y_reset = 18
btn_analog2x_reset = 1082
btn_analog2y_reset = 1083
btn_analog1x_left_alt = 44
btn_analog1x_right_alt = 46
btn_analog1y_down_alt = 56
btn_analog1y_up_alt = 45
btn_analog2x_left_alt = 36
btn_analog2x_right_alt = 38
btn_analog2y_down_alt = 37
btn_analog2y_up_alt = 23
btn_analog1_autocenter_onoff = 2
btn_analog2_autocenter_onoff = 3
btn_trigger_left_autocenter_onoff = 4
btn_trigger_right_autocenter_onoff = 5
btn_fixed_mouse_position_onoff = 6
btn_mouse_limit_onoff = 7
btn_modifier_switches_off = 42
;btn_analog1x_left [a]
;btn_analog1x_right [d]
;btn_analog1y_down [s]
;btn_analog1y_up [w]
;btn_analog2x_left [left]
;btn_analog2x_right [right]
;btn_analog2y_down [down]
;btn_analog2y_up [up]
;btn_dpad_left [f]
;btn_dpad_right [h]
;btn_dpad_down [g]
;btn_dpad_up [t]
;btn_trigger_left [page up]
;btn_trigger_right [page down]
;btn_a [delete]
;btn_b [end]
;btn_x [insert]
;btn_y [home]
;btn_lb [[]
;btn_rb []]
;btn_l3 [´]
;btn_r3 [~]
;btn_back [-]
;btn_start [equal+]
;btn_guide [0]
;btn_stick_alternate_onoff [caps lock]
;btn_trigger_alternate_onoff [right shift]
;btn_trigger_left_low [volume down]
;btn_trigger_left_high [play/pause media]
;btn_trigger_right_low [volume up]
;btn_trigger_right_high [next track]
;btn_trigger_left_reduce [keypad 7]
;btn_trigger_right_reduce [keypad 4]
;btn_analog1x_reset [q]
;btn_analog1y_reset [e]
;btn_analog2x_reset [keypad 0]
;btn_analog2y_reset [keypad decimal]
;btn_analog1x_left_alt [z]
;btn_analog1x_right_alt [c]
;btn_analog1y_down_alt [alt]
;btn_analog1y_up_alt [x]
;btn_analog2x_left_alt [j]
;btn_analog2x_right_alt [l]
;btn_analog2y_down_alt [k]
;btn_analog2y_up_alt [i]
;btn_analog1_autocenter_onoff [1]
;btn_analog2_autocenter_onoff [2]
;btn_trigger_left_autocenter_onoff [3]
;btn_trigger_right_autocenter_onoff [4]
;btn_fixed_mouse_position_onoff [5]
;btn_mouse_limit_onoff [6]
;btn_modifier_switches_off [shift]

